`timescale 1ns / 1ps

// ============================================================================
// Testbench: Full System Interaction
// Verifies drum_set_top.sv interacting with a behavioral BNO085 model
// ============================================================================

module tb_system_full_interaction;

    // Clock and Reset
    logic clk; // Generated by testbench to drive the DUT's internal logic if needed, 
               // OR we rely on DUT generating it.
               // looking at drum_set_top:
               // It has `HSOSC` for hardware.
               // It has `initial begin clk = 0; forever ... end` for simulation (commented out by default?).
               // We need to provide a clock source or modify DUT. 
               // Best approach: Force the 'clk' signal in the DUT from here.
    
    logic rst_n;
    
    // Signals
    logic sclk1, mosi1, miso1, cs_n1, int1;
    logic sclk2, mosi2, miso2, cs_n2, int2;
    logic calib_button = 0, kick_button = 0;
    logic mcu_sclk, mcu_mosi, mcu_cs_n;
    logic led_initialized, led_error;

    // Instantiate DUT
    drum_set_top dut (
        .rst_n(rst_n),
        .sclk1(sclk1),
        .mosi1(mosi1),
        .miso1(miso1),
        .cs_n1(cs_n1),
        .int1(int1),
        .sclk2(sclk2),
        .mosi2(mosi2),
        .miso2(miso2),
        .cs_n2(cs_n2),
        .int2(int2),
        .calib_button(calib_button),
        .kick_button(kick_button),
        .mcu_sclk(mcu_sclk),
        .mcu_mosi(mcu_mosi),
        .mcu_cs_n(mcu_cs_n),
        .led_initialized(led_initialized),
        .led_error(led_error)
    );

    // Clock Generation (Injecting into DUT)
    initial begin
        force dut.clk = 0;
        forever #167 force dut.clk = ~dut.clk; // ~3MHz clock (333ns period)
    end

    // Instantiate Advanced BNO085 Model
    bno085_behavioral_model #(.DEBUG_NAME("IMU1")) imu1 (
        .sclk(sclk1),
        .mosi(mosi1),
        .miso(miso1),
        .cs_n(cs_n1),
        .int_n(int1),
        .rst_n(rst_n)
    );

    // Monitor State
    always @(dut.bno085_ctrl1.state) begin
        $display("[%0t] Controller State: %d", $time, dut.bno085_ctrl1.state);
    end
    
    // Monitor SPI
    always @(negedge sclk1) begin
        if (!cs_n1) $display("[%0t] SPI MISO: %b", $time, miso1);
    end
    
    always @(negedge int1) begin
        $display("[%0t] INT1 Falling Edge (Sensor Ready)", $time);
    end

    // Monitor Initialization
    always @(dut.bno1_initialized) begin
        $display("[%0t] bno1_initialized changed to %b", $time, dut.bno1_initialized);
    end

    // Monitor SPI TX (MOSI) from FPGA to see what it sends
    always @(posedge sclk1) begin
        if (!cs_n1) $display("[%0t] SPI MOSI: %b", $time, mosi1);
    end

    // Test Sequence
    initial begin
        $display("=== Starting Full Interaction Test ===");
        
        // 1. Reset
        rst_n = 0;
        #1000;
        rst_n = 1;
        $display("[%0t] Reset Released", $time);

        // 2. Wait for Initialization
        // The model is programmed to respond to Product ID and Feature Requests.
        // We check Sensor 1 specifically because we only connected one sensor model.
        
        wait(dut.bno1_initialized == 1);
        $display("[%0t] SUCCESS: Sensor 1 Initialized", $time);
        
        // 3. Verify Data Streaming
        // We are now in the data streaming phase.
        // We want to see that we are receiving valid quaternions.
        
        wait(dut.quat1_valid == 1);
        $display("[%0t] SUCCESS: Received Valid Quaternion Data", $time);
        $display("Quat: W=%d X=%d Y=%d Z=%d", dut.quat1_w, dut.quat1_x, dut.quat1_y, dut.quat1_z);
        
        #1000000; // Run for a bit more
        
        $display("=== Test Passed ===");
        $finish;
    end

    // Timeout
    initial begin
        #400000000; // 400ms timeout
        $display("FAIL: Simulation Timeout (400ms)");
        $display("Status: bno1_initialized=%b, quat1_valid=%b, state=%d", dut.bno1_initialized, dut.quat1_valid, dut.bno085_ctrl1.state);
        $finish;
    end

endmodule


// ============================================================================
// Behavioral BNO085 Model
// ============================================================================
module bno085_behavioral_model #(parameter string DEBUG_NAME = "IMU") (
    input logic sclk,
    input logic mosi,
    output logic miso,
    input logic cs_n,
    output logic int_n,
    input logic rst_n
);

    // State
    typedef enum {WAIT_RESET, ASSERT_INT, WAIT_CS, RX_TX, PROCESSING} state_t;
    state_t state = WAIT_RESET;

    // SHTP Header
    logic [7:0] rx_buf [0:255];
    logic [7:0] tx_buf [0:255];
    integer rx_idx = 0;
    integer tx_idx = 0;
    integer bit_idx = 0;
    logic [7:0] rx_byte = 0;
    logic [7:0] tx_byte = 0;

    // Responses
    integer response_queue_len = 0;
    logic [7:0] next_response_type = 0; // 0=None, 1=ProdID, 2=Feature
    logic streaming_enabled = 0;
    logic [7:0] seq = 0;

    initial begin
        int_n = 1;
        miso = 0;
        // Initialize buffer to avoid X
        for (integer i=0; i<256; i++) rx_buf[i] = 0;
    end

    // Main Logic Loop
    always begin
        #100; // Tick
        
        if (rst_n) begin
            case (state)
                WAIT_RESET: begin
                    // Wait a bit after reset then advertise
                    #5000;
                    state = ASSERT_INT;
                end
                
                ASSERT_INT: begin
                    int_n = 0; // Active Low: "I have something / I am ready"
                    if (cs_n == 0) begin
                        state = RX_TX;
                        rx_idx = 0;
                        tx_idx = 0;
                        bit_idx = 0;
                        // Prepare TX buffer based on what we want to send
                        // For now, default to empty header if nothing queued
                        if (response_queue_len == 0) begin
                            tx_buf[0] = 4; tx_buf[1] = 0; tx_buf[2] = 0; tx_buf[3] = 0; // Empty
                            //$display("[%s] Starting TX (Empty). Len=4", DEBUG_NAME);
                        end else begin
                            //$display("[%s] Starting TX. Len=%d. Byte0=0x%02X QLen=%d", DEBUG_NAME, {tx_buf[1], tx_buf[0]}, tx_buf[0], response_queue_len);
                        end
                    end
                end
                
                RX_TX: begin
                    // Handled by SPI block
                    if (cs_n == 1) begin
                        state = PROCESSING;
                        int_n = 1; // Deassert INT
                    end
                end
                
                PROCESSING: begin
                    // Calculate actual received length from header (Bytes 0,1)
                    // Note: Length includes header (4 bytes)
                    // Explicit assignment to update variable every time
                    integer packet_len;
                    packet_len = {rx_buf[1], rx_buf[0]};
                    
                    $display("[%s] Processing Packet. Len=%d. Byte0=0x%02X Byte4=0x%02X Stream=%b QLen=%d", 
                        DEBUG_NAME, packet_len, rx_buf[0], rx_buf[4], streaming_enabled, response_queue_len);
                    
                    // Analyze what we received
                    // Only check payload if packet_len > 4
                    if (packet_len > 4 && rx_buf[2] == 0 && rx_buf[4] == 8'hF9) begin
                        $display("[%s] Received Product ID Request", DEBUG_NAME);
                        // Queue Product ID Response
                        tx_buf[0] = 20; tx_buf[1] = 0; tx_buf[2] = 0; tx_buf[3] = 0;
                        tx_buf[4] = 8'hF8; // Product ID Response
                        // ... fill rest with dummy ...
                        response_queue_len = 1;
                    end
                    else if (packet_len > 4 && rx_buf[4] == 8'hFD) begin // Set Feature
                        $display("[%s] Received Set Feature Request", DEBUG_NAME);
                        // Queue Empty Response (Ack)
                        tx_buf[0] = 4; tx_buf[1] = 0; tx_buf[2] = 0; tx_buf[3] = 0;
                        response_queue_len = 1;
                        // Enable streaming flag
                        streaming_enabled = 1;
                    end
                    else if (streaming_enabled) begin
                         // Send Rotation Vector Report
                         // Header: Len=20, Ch=5 (Reports), Seq=0
                         tx_buf[0] = 20; tx_buf[1] = 0; tx_buf[2] = 5; tx_buf[3] = seq++;
                         // Report: ID=5 (RotVec), Seq=0, Status=0, Delay=0
                         tx_buf[4] = 5; tx_buf[5] = seq; tx_buf[6] = 0; tx_buf[7] = 0;
                         // Data (Quat) - valid Q14
                         tx_buf[8] = 0; tx_buf[9] = 0; // i
                         tx_buf[10] = 0; tx_buf[11] = 0; // j
                         tx_buf[12] = 0; tx_buf[13] = 0; // k
                         tx_buf[14] = 0; tx_buf[15] = 64; // real (1.0 in Q14 = 16384 = 0x4000)
                         tx_buf[16] = 0; tx_buf[17] = 0; // accuracy
                         
                         $display("[%s] Queuing Rotation Vector Report (Seq %d)", DEBUG_NAME, seq);
                         response_queue_len = 1;
                    end
                    
                    #5000; // Processing time
                    state = ASSERT_INT; // Ready for next transaction
                end
            endcase
        end
    end

    // SPI Slave Logic
    always @(negedge sclk) begin // Shift Out (MISO)
        if (!cs_n) begin
            tx_byte = tx_buf[tx_idx];
            miso <= tx_byte[7 - bit_idx];
        end
    end
    
    always @(posedge sclk) begin // Shift In (MOSI)
        if (!cs_n) begin
            rx_byte[7 - bit_idx] = mosi;
            
            bit_idx++;
            if (bit_idx == 8) begin
                rx_buf[rx_idx] = rx_byte;
                rx_idx++;
                tx_idx++;
                bit_idx = 0;
            end
        end
    end

endmodule
