// Top-level Drum System Module - GYRO-ONLY VERSION
// CRITICAL: Must instantiate I2C IP wrapper from Module Generator
// Uses only gyroscope data for gesture recognition
// Author: E155 Final Project
// Date: 2024

module drum_system_top (
    input  logic        clk_ext,
    input  logic        rst_n,
    // I2C Physical Pins (connect to BNO055)
    inout  logic        i2c1_scl,  // I2C1 SCL (physical pin)
    inout  logic        i2c1_sda,  // I2C1 SDA (physical pin)
    input  logic        button1,
    input  logic        button2,
    output logic        led1,
    output logic        led2,
    output logic [7:0]  sound_id
);
    
    logic clk;
    
`ifdef SIMULATION
    assign clk = clk_ext;
`else
    HSOSC #(.CLKHF_DIV(2'b11)) hf_osc (
        .CLKHFPU(1'b1), 
        .CLKHFEN(1'b1), 
        .CLKHF(clk)
    );
    (* keep *) wire _unused_clk_ext = clk_ext;
`endif

    // Internal System Bus signals (connect to I2C IP wrapper)
    logic        i2c1_sb_clk;
    logic        i2c1_sb_wr;
    logic        i2c1_sb_stb;
    logic [7:0]  i2c1_sb_addr;
    logic [7:0]  i2c1_sb_data_i;
    logic [7:0]  i2c1_sb_data_o;
    logic        i2c1_sb_ack;
    logic        i2c1_irq;
    logic        i2c1_ipload;
    logic        i2c1_ipdone;
    
    // Gyroscope data
    logic signed [15:0] gyro_x, gyro_y, gyro_z;
    logic imu_data_valid;
    
    // Debouncing
    logic button1_db;
    logic [15:0] debounce_counter;
    localparam DEBOUNCE_COUNT = 3000;
    
    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            debounce_counter <= 0;
            button1_db <= 0;
        end else begin
            if (debounce_counter < DEBOUNCE_COUNT) begin
                debounce_counter <= debounce_counter + 16'd1;
            end else begin
                debounce_counter <= 0;
                button1_db <= button1;
            end
        end
    end
    
    // I2C IP initialization
    logic i2c1_ready;
    
    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            i2c1_ipload <= 0;
            i2c1_ready <= 0;
        end else begin
            if (!i2c1_ready) begin
                i2c1_ipload <= 1;
                if (i2c1_ipdone) begin
                    i2c1_ready <= 1;
                end
            end
        end
    end
    
    assign i2c1_sb_clk = clk;
    
    // ============================================================================
    // CRITICAL: INSTANTIATE I2C IP WRAPPER (Generated by Module Generator)
    // ============================================================================
    // NOTE: Replace "i2c_master_top" with the ACTUAL module name from your generated IP
    // Check the generated .v or .sv file for exact module name and port names
    // ============================================================================
    
    // TODO: Uncomment and use correct module name from your generated IP
    /*
    i2c_master_top i2c1_ip (
        // System Bus Clock
        .SBCLKi(i2c1_sb_clk),
        
        // System Bus Interface
        .SBWRi(i2c1_sb_wr),
        .SBSTBi(i2c1_sb_stb),
        .SBADRi(i2c1_sb_addr),
        .SBDATi(i2c1_sb_data_i),
        .SBDATo(i2c1_sb_data_o),
        .SBACKo(i2c1_sb_ack),
        .I2CPIRQ(i2c1_irq),
        
        // IP Configuration
        .IPLOAD(i2c1_ipload),
        .IPDONE(i2c1_ipdone),
        
        // I2C Physical Pins
        .I2C1_SCL(i2c1_scl),
        .I2C1_SDA(i2c1_sda)
    );
    */
    
    // TEMPORARY: Direct connection for testing (remove when IP is instantiated)
    // This allows synthesis to proceed but I2C won't work
    assign i2c1_sb_wr = 0;
    assign i2c1_sb_stb = 0;
    assign i2c1_sb_addr = 0;
    assign i2c1_sb_data_i = 0;
    assign i2c1_sb_ack = 0;
    assign i2c1_irq = 0;
    assign i2c1_ipdone = 1;  // Assume IP is ready for now
    
    // BNO055 I2C Controller - GYRO ONLY
    bno055_i2c_controller_gyro_only imu_controller (
        .clk(clk),
        .rst_n(rst_n && i2c1_ready),
        // REMOVED: .sb_clk(i2c1_sb_clk),  // Not used in controller
        .sb_wr(i2c1_sb_wr),
        .sb_stb(i2c1_sb_stb),
        .sb_addr(i2c1_sb_addr),
        .sb_data_i(i2c1_sb_data_i),
        .sb_data_o(i2c1_sb_data_o),
        .sb_ack(i2c1_sb_ack),
        .sb_irq(i2c1_irq),
        .gyro_x(gyro_x),
        .gyro_y(gyro_y),
        .gyro_z(gyro_z),
        .data_valid(imu_data_valid)
    );
    
    // Gesture recognition - GYRO ONLY
    gesture_recognition_gyro_only gesture_rec (
        .clk(clk),
        .rst_n(rst_n),
        .gyro_y(gyro_y),
        .gyro_z(gyro_z),
        .button1(button1_db),
        .sound_id(sound_id)
    );
    
    assign led1 = (sound_id != 8'hFF);
    assign led2 = 1'b0;

endmodule
