// Top-level Drum System Module for iCE40 FPGA
// Uses hardened I2C IP blocks to communicate with BNO055 IMU sensors
// Implements gesture recognition and outputs drum sound IDs
// Author: E155 Final Project
// Date: 2024
//
// Note: I2C physical pins (SCL/SDA) are handled internally by the I2C IP
// wrapper generated by Module Generator. Only System Bus interface is exposed.

module drum_system_top (
    // Clock and Reset
    // For simulation: provide external clk
    // For synthesis: uses HSOSC internally at 3MHz (see clock generation below)
    input  logic        clk_ext,      // External clock input (for simulation)
    input  logic        rst_n,
    
    // System Bus Interface for I2C1 (Left I2C - IMU 1)
    // These connect to the Soft IP wrapper generated by Module Generator
    // According to datasheet: Module Generator creates Soft IP wrapper around Hard IP
    output logic        i2c1_sb_clk,      // SBCLKi - System clock input
    output logic        i2c1_sb_wr,      // SBWRi - Read/Write (0=read, 1=write)
    output logic        i2c1_sb_stb,     // SBSTBi - Strobe signal
    output logic [7:0]  i2c1_sb_addr,    // SBADRi[7:0] - Register address
    output logic [7:0]  i2c1_sb_data_i,  // SBDATi[7:0] - Data input
    input  logic [7:0]  i2c1_sb_data_o,  // SBDATo[7:0] - Data output
    input  logic        i2c1_sb_ack,     // SBACKo - Acknowledge
    input  logic        i2c1_irq,        // I2CPIRQ - Interrupt request
    // Soft IP wrapper control signals (from Module Generator)
    output logic        i2c1_ipload,     // IPLOAD - Start IP configuration
    input  logic        i2c1_ipdone,     // IPDONE - IP configuration complete
    
    // System Bus Interface for I2C2 (Right I2C - IMU 2)
    // These connect to the Soft IP wrapper generated by Module Generator
    output logic        i2c2_sb_clk,      // SBCLKi - System clock input
    output logic        i2c2_sb_wr,      // SBWRi - Read/Write (0=read, 1=write)
    output logic        i2c2_sb_stb,     // SBSTBi - Strobe signal
    output logic [7:0]  i2c2_sb_addr,    // SBADRi[7:0] - Register address
    output logic [7:0]  i2c2_sb_data_i,  // SBDATi[7:0] - Data input
    input  logic [7:0]  i2c2_sb_data_o,  // SBDATo[7:0] - Data output
    input  logic        i2c2_sb_ack,     // SBACKo - Acknowledge
    input  logic        i2c2_irq,        // I2CPIRQ - Interrupt request
    // Soft IP wrapper control signals (from Module Generator)
    output logic        i2c2_ipload,     // IPLOAD - Start IP configuration
    input  logic        i2c2_ipdone,     // IPDONE - IP configuration complete
    
    // User Interface
    input  logic        button1,      // Kick drum
    input  logic        button2,      // Calibration
    output logic        led1,         // Status LED
    output logic        led2,         // Status LED
    
    // Audio Output
    output logic [7:0]  sound_id      // Drum sound ID (0-7, 255 = no sound)
);
    
    // Clock generation: Use internal oscillator for synthesis, external for simulation
    // This allows Questa simulation to work while using HSOSC in hardware
    logic clk;
    
`ifdef SIMULATION
    // For simulation: use external clock directly
    assign clk = clk_ext;
`else
    // HARDWARE CLOCK - HSOSC (ACTIVE FOR HARDWARE)
    // CLKHF_DIV(2'b11) = divide by 16 to get 3MHz from 48MHz
    HSOSC #(.CLKHF_DIV(2'b11)) hf_osc (
        .CLKHFPU(1'b1), 
        .CLKHFEN(1'b1), 
        .CLKHF(clk)
    );
`endif

    // Internal signals for IMU 1 (Right Hand)
    logic [15:0] quat1_w, quat1_x, quat1_y, quat1_z;
    logic signed [15:0] gyro1_x, gyro1_y, gyro1_z;  // Gyro values are signed
    logic signed [15:0] yaw1, pitch1, roll1;
    logic imu1_data_valid;
    
    // Internal signals for IMU 2 (Left Hand)
    logic [15:0] quat2_w, quat2_x, quat2_y, quat2_z;
    logic signed [15:0] gyro2_x, gyro2_y, gyro2_z;  // Gyro values are signed
    logic signed [15:0] yaw2, pitch2, roll2;
    logic imu2_data_valid;
    
    // Calibration offsets
    logic signed [15:0] yaw_offset1, yaw_offset2;
    logic signed [15:0] yaw1_normalized, yaw2_normalized;  // Signed for gesture_recognition
    
    // Debouncing
    logic button1_db, button2_db;
    logic [15:0] debounce_counter;
    
    // Debounce buttons
    // Adjust counter based on clock frequency
    // For 3MHz (hardware): ~3000 counts = 1ms
    // For 48MHz: ~48000 counts = 1ms
    // For 16MHz: ~16000 counts = 1ms
    // For simulation: use smaller value for faster simulation
    localparam DEBOUNCE_COUNT = 3000;  // 1ms debounce at 3MHz (hardware clock)
    
    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            debounce_counter <= 0;
            button1_db <= 0;
            button2_db <= 0;
        end else begin
            if (debounce_counter < DEBOUNCE_COUNT) begin
                debounce_counter <= debounce_counter + 1;
            end else begin
                debounce_counter <= 0;
                button1_db <= button1;
                button2_db <= button2;
            end
        end
    end
    
    // Calibration: Store current yaw as offset
    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            yaw_offset1 <= 0;
            yaw_offset2 <= 0;
        end else if (button2_db) begin
            yaw_offset1 <= yaw1;
            yaw_offset2 <= yaw2;
        end
    end
    
    // Normalize yaw (subtract offset and wrap to 0-36000, where 36000 = 360.00 degrees)
    logic signed [15:0] yaw1_temp, yaw2_temp;
    assign yaw1_temp = yaw1 - yaw_offset1;
    assign yaw2_temp = yaw2 - yaw_offset2;
    
    // Normalize yaw to 0-36000 range (unsigned for gesture recognition)
    // Gesture recognition expects unsigned yaw in 0-36000 range
    logic [15:0] yaw1_normalized_unsigned, yaw2_normalized_unsigned;
    
    always_comb begin
        // Wrap yaw1 to 0-36000 range (convert signed to unsigned)
        if (yaw1_temp < 0) begin
            yaw1_normalized_unsigned = yaw1_temp + 16'd36000;
        end else if (yaw1_temp >= 16'd36000) begin
            yaw1_normalized_unsigned = yaw1_temp - 16'd36000;
        end else begin
            yaw1_normalized_unsigned = yaw1_temp[15:0];
        end
        
        // Wrap yaw2 to 0-36000 range (convert signed to unsigned)
        if (yaw2_temp < 0) begin
            yaw2_normalized_unsigned = yaw2_temp + 16'd36000;
        end else if (yaw2_temp >= 16'd36000) begin
            yaw2_normalized_unsigned = yaw2_temp - 16'd36000;
        end else begin
            yaw2_normalized_unsigned = yaw2_temp[15:0];
        end
    end
    
    // Convert to signed for gesture recognition (it will normalize internally)
    assign yaw1_normalized = $signed(yaw1_normalized_unsigned);
    assign yaw2_normalized = $signed(yaw2_normalized_unsigned);
    
    // I2C IP initialization: Set IPLOAD and wait for IPDONE
    // According to datasheet: IPDONE = 1 when Hard IP Configuration is complete
    // Set IPLOAD = 1 and wait for IPDONE = 1 before IP can be fully utilized
    logic i2c1_ready, i2c2_ready;
    
    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            i2c1_ipload <= 0;
            i2c2_ipload <= 0;
            i2c1_ready <= 0;
            i2c2_ready <= 0;
        end else begin
            // Initialize I2C1: Set IPLOAD, wait for IPDONE
            if (!i2c1_ready) begin
                i2c1_ipload <= 1;
                if (i2c1_ipdone) begin
                    i2c1_ready <= 1;
                end
            end
            
            // Initialize I2C2: Set IPLOAD, wait for IPDONE
            if (!i2c2_ready) begin
                i2c2_ipload <= 1;
                if (i2c2_ipdone) begin
                    i2c2_ready <= 1;
                end
            end
        end
    end
    
    // System Bus clock assignment (must match system clock)
    assign i2c1_sb_clk = clk;
    assign i2c2_sb_clk = clk;
    
    // BNO055 I2C Controller for IMU 1 (Right Hand)
    // Only enable when I2C IP is ready (IPDONE = 1)
    bno055_i2c_controller imu1_controller (
        .clk(clk),
        .rst_n(rst_n && i2c1_ready),  // Reset until I2C IP is ready
        .sb_clk(i2c1_sb_clk),
        .sb_wr(i2c1_sb_wr),
        .sb_stb(i2c1_sb_stb),
        .sb_addr(i2c1_sb_addr),
        .sb_data_i(i2c1_sb_data_i),
        .sb_data_o(i2c1_sb_data_o),
        .sb_ack(i2c1_sb_ack),
        .sb_irq(i2c1_irq),
        .quat_w(quat1_w),
        .quat_x(quat1_x),
        .quat_y(quat1_y),
        .quat_z(quat1_z),
        .gyro_x(gyro1_x),
        .gyro_y(gyro1_y),
        .gyro_z(gyro1_z),
        .data_valid(imu1_data_valid)
    );
    
    // BNO055 I2C Controller for IMU 2 (Left Hand)
    // Only enable when I2C IP is ready (IPDONE = 1)
    bno055_i2c_controller imu2_controller (
        .clk(clk),
        .rst_n(rst_n && i2c2_ready),  // Reset until I2C IP is ready
        .sb_clk(i2c2_sb_clk),
        .sb_wr(i2c2_sb_wr),
        .sb_stb(i2c2_sb_stb),
        .sb_addr(i2c2_sb_addr),
        .sb_data_i(i2c2_sb_data_i),
        .sb_data_o(i2c2_sb_data_o),
        .sb_ack(i2c2_sb_ack),
        .sb_irq(i2c2_irq),
        .quat_w(quat2_w),
        .quat_x(quat2_x),
        .quat_y(quat2_y),
        .quat_z(quat2_z),
        .gyro_x(gyro2_x),
        .gyro_y(gyro2_y),
        .gyro_z(gyro2_z),
        .data_valid(imu2_data_valid)
    );
    
    // Quaternion to Euler converter for IMU 1
    quaternion_to_euler quat_to_euler1 (
        .clk(clk),
        .rst_n(rst_n),
        .data_valid(imu1_data_valid),
        .quat_w(quat1_w),
        .quat_x(quat1_x),
        .quat_y(quat1_y),
        .quat_z(quat1_z),
        .yaw(yaw1),
        .pitch(pitch1),
        .roll(roll1),
        .euler_valid()
    );
    
    // Quaternion to Euler converter for IMU 2
    quaternion_to_euler quat_to_euler2 (
        .clk(clk),
        .rst_n(rst_n),
        .data_valid(imu2_data_valid),
        .quat_w(quat2_w),
        .quat_x(quat2_x),
        .quat_y(quat2_y),
        .quat_z(quat2_z),
        .yaw(yaw2),
        .pitch(pitch2),
        .roll(roll2),
        .euler_valid()
    );
    
    // Gesture recognition module
    gesture_recognition gesture_rec (
        .clk(clk),
        .rst_n(rst_n),
        .yaw1(yaw1_normalized),
        .pitch1(pitch1),
        .gyro1_y(gyro1_y),
        .yaw2(yaw2_normalized),
        .pitch2(pitch2),
        .gyro2_y(gyro2_y),
        .gyro2_z(gyro2_z),
        .button1(button1_db),
        .sound_id(sound_id)
    );
    
    // LED control
    assign led1 = (sound_id != 8'hFF);
    assign led2 = button2_db;

endmodule
Warning	35935050	Synthesis	WARNING <35935050> - input port TRIM9 is not connected on this instance. VDB-5050	
Info	35901328	Synthesis	INFO <35901328> - c:/lscc/radiant/2024.2/ip/pmi/pmi_ice40up.v(1): analyzing included file c:/lscc/radiant/2024.2/ip/pmi/pmi_addsub.v. VERI-1328 [pmi_ice40up.v:1]	
Info	35921014	Synthesis	INFO <35921014> - c:/lscc/radiant/2024.2/ip/pmi/pmi_ice40up.vhd(4): analyzing package components. VHDL-1014 [pmi_ice40up.vhd:4]	
Info	35921504	Synthesis	INFO <35921504> - The default VHDL library search path is now "C:/Users/mbellido/Desktop/mb/drumsi2c/impl_1". VHDL-1504	
Info	35901018	Synthesis	INFO <35901018> - c:/users/mbellido/desktop/mb/drumsi2c/drum_system_top.sv(10): compiling module drum_system_top. VERI-1018 [drum_system_top.sv:10]	
Warning	35901209	Synthesis	WARNING <35901209> - c:/users/mbellido/desktop/mb/drumsi2c/drum_system_top.sv(108): expression size 32 truncated to fit in target size 16. VERI-1209 [drum_system_top.sv:108]	
Critical	35001747	Synthesis	CRITICAL <35001747> - Bit(s) of register driving quaternion_to_euler/roll_den_reg[31:0] stuck at '0': 0	
Critical	35002028	Synthesis	CRITICAL <35002028> - I/O port's net has no driver and is unused: clk_ext	
Warning	35935040	Synthesis	WARNING <35935040> - Register \gesture_rec/printedForGyro1y_2 clock is stuck at Zero. VDB-5040	
Info	35001774	Synthesis	INFO <35001774> - Extracted state machine for register '\imu1_controller/sb_master/state' with one-hot encoding	
Warning	35001714	Synthesis	WARNING <35001714> - Net gnd has following drivers :	
Error	35931000	Synthesis	ERROR <35931000> - c:/users/mbellido/desktop/mb/drumsi2c/gesture_recognition.sv(237): net gnd is constantly driven from multiple places at instance \gesture_rec/printedForGyro1y, on port q. VDB-1000 [gesture_recognition.sv:237]	
Synthesis (1 errors, 23 criticals, 29 warnings, 45 info)	

new errors:Critical	35001476	Synthesis	CRITICAL <35001476> - A top-level module has not been specified for the mixed language design.	
Warning	35935050	Synthesis	WARNING <35935050> - input port TRIM9 is not connected on this instance. VDB-5050	
Info	35901328	Synthesis	INFO <35901328> - c:/lscc/radiant/2024.2/ip/pmi/pmi_ice40up.v(1): analyzing included file c:/lscc/radiant/2024.2/ip/pmi/pmi_addsub.v. VERI-1328 [pmi_ice40up.v:1]	
Info	35921014	Synthesis	INFO <35921014> - c:/lscc/radiant/2024.2/ip/pmi/pmi_ice40up.vhd(4): analyzing package components. VHDL-1014 [pmi_ice40up.vhd:4]	
Warning	35001200	Synthesis	WARNING <35001200> - Setting drum_system_top as the top-level module. To specify the top-level module explicitly, go to View->Set Views->Hierarchy or Project->Active Implementation->Set Top-Level Unit.	
Info	35921504	Synthesis	INFO <35921504> - The default VHDL library search path is now "C:/Users/mbellido/Desktop/mb/drumsi2c/impl_1". VHDL-1504	
Info	35901018	Synthesis	INFO <35901018> - c:/users/mbellido/desktop/mb/drumsi2c/drum_system_top.sv(10): compiling module drum_system_top. VERI-1018 [drum_system_top.sv:10]	
Warning	35901209	Synthesis	WARNING <35901209> - c:/users/mbellido/desktop/mb/drumsi2c/drum_system_top.sv(108): expression size 32 truncated to fit in target size 16. VERI-1209 [drum_system_top.sv:108]	
Critical	35001747	Synthesis	CRITICAL <35001747> - Bit(s) of register driving quaternion_to_euler/roll_den_reg[31:0] stuck at '0': 0	
Critical	35002028	Synthesis	CRITICAL <35002028> - I/O port's net has no driver and is unused: clk_ext	
Info	35001774	Synthesis	INFO <35001774> - Extracted state machine for register '\imu1_controller/sb_master/state' with one-hot encoding	
Warning	35001714	Synthesis	WARNING <35001714> - Net i2c2_sb_data_i_2 has following drivers :	
Error	35931000	Synthesis	ERROR <35931000> - c:/users/mbellido/desktop/mb/drumsi2c/bno055_i2c_controller.sv(184): net i2c2_sb_data_i_2 is constantly driven from multiple places at instance \imu1_controller/delay_counter_2_1250__i0, on port q. VDB-1000 [bno055_i2c_controller.sv:184]	
Synthesis (1 errors, 28 criticals, 24 warnings, 45 info)	

