// Top-level Drum System Module - GYRO-ONLY VERSION WITH I2C IP
// CRITICAL: Must instantiate I2C IP wrapper generated by Module Generator
// Uses only gyroscope data for gesture recognition
// Author: E155 Final Project
// Date: 2024

module drum_system_top (
    input  logic        clk_ext,
    input  logic        rst_n,
    
    // I2C Physical Pins (connect to BNO055 sensor)
    // These are handled by the I2C IP wrapper
    inout  wire         i2c1_scl,  // I2C1 SCL (physical pin)
    inout  wire         i2c1_sda,  // I2C1 SDA (physical pin)
    
    // User Interface
    input  logic        button1,
    input  logic        button2,
    output logic        led1,
    output logic        led2,
    output logic [7:0]  sound_id
);
    
    logic clk;
    
`ifdef SIMULATION
    assign clk = clk_ext;
`else
    HSOSC #(.CLKHF_DIV(2'b11)) hf_osc (
        .CLKHFPU(1'b1), 
        .CLKHFEN(1'b1), 
        .CLKHF(clk)
    );
    (* keep *) wire _unused_clk_ext = clk_ext;
`endif

    // System Bus signals for I2C1 (connect to I2C IP wrapper)
    logic        i2c1_sb_clk;
    logic        i2c1_sb_wr;
    logic        i2c1_sb_stb;
    logic [7:0]  i2c1_sb_addr;
    logic [7:0]  i2c1_sb_data_i;
    logic [7:0]  i2c1_sb_data_o;
    logic        i2c1_sb_ack;
    logic [1:0]  i2c_pirq_o;  // I2C interrupt vector [1:0] from IP
    logic        i2c1_irq;    // Extracted I2C1 interrupt
    logic        i2c1_ipload;
    logic        i2c1_ipdone;
    
    // Assign System Bus clock
    assign i2c1_sb_clk = clk;
    
    // ============================================================================
    // INSTANTIATE I2C1 IP WRAPPER (Generated by Module Generator)
    // ============================================================================
    // CRITICAL: Make sure the generated i2c_block.v file is added to your Radiant project!
    // The I2C IP block must be included as a source file for synthesis to work.
    // Module name: i2c_block (from Module Generator)
    
    // I2C IP Block Instantiation
    // CRITICAL: The Module Generator file at E155_finalp/i2c_block/rtl/i2c_block.v
    // has different port names. You MUST either:
    // 1. Replace that file with our repository's i2c_block.v, OR
    // 2. Check that file's port names and update this instantiation
    //
    // Our repository's i2c_block.v has these ports:
    // i2c2_scl_io, i2c2_sda_io, i2c1_scl_io, i2c1_sda_io, rst_i, ipload_i, ipdone_o,
    // sb_clk_i, sb_wr_i, sb_stb_i, sb_adr_i, sb_dat_i, sb_dat_o, sb_ack_o, i2c_pirq_o, i2c_pwkup_o
    //
    // If your Module Generator file has different port names, update the connections below.
    i2c_block i2c1_ip (
        // I2C Physical Pins
        // NOTE: If error persists, check E155_finalp/i2c_block/rtl/i2c_block.v for actual port names
        .i2c2_scl_io(1'bZ),              // I2C Left (unused) - may not exist if only I2C Right enabled
        .i2c2_sda_io(1'bZ),              // I2C Left (unused) - may not exist if only I2C Right enabled
        .i2c1_scl_io(i2c1_scl),          // I2C Right (USED) - this is I2C1
        .i2c1_sda_io(i2c1_sda),          // I2C Right (USED) - this is I2C1
        
        // Reset and IP Configuration
        .rst_i(!rst_n),                  // Active-high reset
        .ipload_i(i2c1_ipload),          // IP Load
        .ipdone_o(i2c1_ipdone),          // IP Done
        
        // System Bus Interface
        .sb_clk_i(i2c1_sb_clk),          // System Bus Clock
        .sb_wr_i(i2c1_sb_wr),            // System Bus Write
        .sb_stb_i(i2c1_sb_stb),          // System Bus Strobe
        .sb_adr_i(i2c1_sb_addr),         // System Bus Address
        .sb_dat_i(i2c1_sb_data_i),      // System Bus Data Input
        .sb_dat_o(i2c1_sb_data_o),       // System Bus Data Output
        .sb_ack_o(i2c1_sb_ack),          // System Bus Acknowledge
        .i2c_pirq_o(i2c_pirq_o),         // I2C Interrupt [1:0]
        .i2c_pwkup_o()                   // I2C Wakeup [1:0] (unused)
    );
    
    // Extract I2C1 interrupt from vector
    // Note: I2C1 uses bit 0, I2C2 uses bit 1 (but I2C2 is disabled)
    assign i2c1_irq = i2c_pirq_o[0];
    
    // I2C IP initialization
    logic i2c1_ready;
    
    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            i2c1_ipload <= 0;
            i2c1_ready <= 0;
        end else begin
            if (!i2c1_ready) begin
                i2c1_ipload <= 1;
                if (i2c1_ipdone) begin
                    i2c1_ready <= 1;
                end
            end
        end
    end
    
    // Internal signals
    logic signed [15:0] gyro_x, gyro_y, gyro_z;
    logic imu_data_valid;
    
    // Debouncing
    logic button1_db;
    logic [15:0] debounce_counter;
    localparam DEBOUNCE_COUNT = 3000;
    
    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            debounce_counter <= 0;
            button1_db <= 0;
        end else begin
            if (debounce_counter < DEBOUNCE_COUNT) begin
                debounce_counter <= debounce_counter + 16'd1;
            end else begin
                debounce_counter <= 0;
                button1_db <= button1;
            end
        end
    end
    
    // BNO055 I2C Controller - GYRO ONLY
    // Only enable when I2C IP is ready (IPDONE = 1)
    bno055_i2c_controller_gyro_only imu_controller (
        .clk(clk),
        .rst_n(rst_n && i2c1_ready),
        .sb_clk(i2c1_sb_clk),
        .sb_wr(i2c1_sb_wr),
        .sb_stb(i2c1_sb_stb),
        .sb_addr(i2c1_sb_addr),
        .sb_data_i(i2c1_sb_data_i),
        .sb_data_o(i2c1_sb_data_o),
        .sb_ack(i2c1_sb_ack),
        .sb_irq(i2c1_irq),
        .gyro_x(gyro_x),
        .gyro_y(gyro_y),
        .gyro_z(gyro_z),
        .data_valid(imu_data_valid)
    );
    
    // Gesture recognition - GYRO ONLY (no yaw/pitch)
    gesture_recognition_gyro_only gesture_rec (
        .clk(clk),
        .rst_n(rst_n),
        .gyro_y(gyro_y),
        .gyro_z(gyro_z),
        .button1(button1_db),
        .sound_id(sound_id)
    );
    
    assign led1 = (sound_id != 8'hFF);
    assign led2 = 1'b0;

endmodule
