// Top-level Drum System Module with I2C IP Instantiation
// This shows how to instantiate the I2C IP wrappers generated by Module Generator
// Author: E155 Final Project
// Date: 2024
//
// NOTE: This is a reference file showing I2C IP instantiation.
// Your actual top module may have different port names based on generated IP.

module drum_system_top (
    // Clock and Reset
    input  logic        clk_ext,
    input  logic        rst_n,
    
    // I2C Physical Pins (these connect to BNO055 sensors)
    // Note: These are handled by the I2C IP wrapper, but you may need to expose them
    // depending on how Module Generator generates the wrapper
    inout  logic        i2c1_scl,  // I2C1 SCL (physical pin)
    inout  logic        i2c1_sda,  // I2C1 SDA (physical pin)
    inout  logic        i2c2_scl,  // I2C2 SCL (physical pin)
    inout  logic        i2c2_sda,  // I2C2 SDA (physical pin)
    
    // User Interface
    input  logic        button1,
    input  logic        button2,
    output logic        led1,
    output logic        led2,
    output logic [7:0]  sound_id
);

    // Clock generation
    logic clk;
`ifdef SIMULATION
    assign clk = clk_ext;
`else
    HSOSC #(.CLKHF_DIV(2'b11)) hf_osc (
        .CLKHFPU(1'b1), 
        .CLKHFEN(1'b1), 
        .CLKHF(clk)
    );
`endif

    // System Bus signals for I2C1
    logic        i2c1_sb_clk;
    logic        i2c1_sb_wr;
    logic        i2c1_sb_stb;
    logic [7:0]  i2c1_sb_addr;
    logic [7:0]  i2c1_sb_data_i;
    logic [7:0]  i2c1_sb_data_o;
    logic        i2c1_sb_ack;
    logic        i2c1_irq;
    logic        i2c1_ipload;
    logic        i2c1_ipdone;
    
    // System Bus signals for I2C2
    logic        i2c2_sb_clk;
    logic        i2c2_sb_wr;
    logic        i2c2_sb_stb;
    logic [7:0]  i2c2_sb_addr;
    logic [7:0]  i2c2_sb_data_i;
    logic [7:0]  i2c2_sb_data_o;
    logic        i2c2_sb_ack;
    logic        i2c2_irq;
    logic        i2c2_ipload;
    logic        i2c2_ipdone;
    
    // Assign System Bus clock
    assign i2c1_sb_clk = clk;
    assign i2c2_sb_clk = clk;
    
    // ============================================================================
    // INSTANTIATE I2C1 IP WRAPPER (Generated by Module Generator)
    // ============================================================================
    // NOTE: Replace "i2c_master_top" with the actual module name from your generated IP
    // Check the generated .v or .sv file for exact module name and port names
    
    i2c_master_top i2c1_ip (
        // Clock and Reset (check generated IP for exact names)
        .SBCLKi(i2c1_sb_clk),      // System Bus Clock
        // .RST_N(rst_n),           // Reset (if present in generated IP)
        
        // System Bus Interface
        .SBWRi(i2c1_sb_wr),        // System Bus Write (0=read, 1=write)
        .SBSTBi(i2c1_sb_stb),      // System Bus Strobe
        .SBADRi(i2c1_sb_addr),     // System Bus Address
        .SBDATi(i2c1_sb_data_i),   // System Bus Data Input
        .SBDATo(i2c1_sb_data_o),   // System Bus Data Output
        .SBACKo(i2c1_sb_ack),      // System Bus Acknowledge
        .I2CPIRQ(i2c1_irq),        // I2C Interrupt
        
        // IP Configuration (from Module Generator)
        .IPLOAD(i2c1_ipload),      // IP Load (start configuration)
        .IPDONE(i2c1_ipdone),      // IP Done (configuration complete)
        
        // I2C Physical Pins
        // NOTE: Port names may vary - check your generated IP file
        .I2C1_SCL(i2c1_scl),       // I2C1 Clock (physical pin)
        .I2C1_SDA(i2c1_sda)        // I2C1 Data (physical pin)
    );
    
    // ============================================================================
    // INSTANTIATE I2C2 IP WRAPPER (Generated by Module Generator)
    // ============================================================================
    
    i2c_master_top i2c2_ip (
        // Clock and Reset
        .SBCLKi(i2c2_sb_clk),
        
        // System Bus Interface
        .SBWRi(i2c2_sb_wr),
        .SBSTBi(i2c2_sb_stb),
        .SBADRi(i2c2_sb_addr),
        .SBDATi(i2c2_sb_data_i),
        .SBDATo(i2c2_sb_data_o),
        .SBACKo(i2c2_sb_ack),
        .I2CPIRQ(i2c2_irq),
        
        // IP Configuration
        .IPLOAD(i2c2_ipload),
        .IPDONE(i2c2_ipdone),
        
        // I2C Physical Pins
        .I2C2_SCL(i2c2_scl),       // I2C2 Clock (physical pin)
        .I2C2_SDA(i2c2_sda)        // I2C2 Data (physical pin)
    );
    
    // ============================================================================
    // REST OF YOUR DESIGN (I2C Controllers, Quaternion Math, Gesture Recognition)
    // ============================================================================
    
    // Internal signals for IMU data
    logic [15:0] quat1_w, quat1_x, quat1_y, quat1_z;
    logic signed [15:0] gyro1_x, gyro1_y, gyro1_z;
    logic signed [15:0] yaw1, pitch1, roll1;
    logic imu1_data_valid;
    
    logic [15:0] quat2_w, quat2_x, quat2_y, quat2_z;
    logic signed [15:0] gyro2_x, gyro2_y, gyro2_z;
    logic signed [15:0] yaw2, pitch2, roll2;
    logic imu2_data_valid;
    
    // I2C IP initialization
    logic i2c1_ready, i2c2_ready;
    
    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            i2c1_ipload <= 0;
            i2c2_ipload <= 0;
            i2c1_ready <= 0;
            i2c2_ready <= 0;
        end else begin
            if (!i2c1_ready) begin
                i2c1_ipload <= 1;
                if (i2c1_ipdone) begin
                    i2c1_ready <= 1;
                end
            end
            
            if (!i2c2_ready) begin
                i2c2_ipload <= 1;
                if (i2c2_ipdone) begin
                    i2c2_ready <= 1;
                end
            end
        end
    end
    
    // BNO055 I2C Controller for IMU 1
    bno055_i2c_controller imu1_controller (
        .clk(clk),
        .rst_n(rst_n && i2c1_ready),
        .sb_clk(i2c1_sb_clk),
        .sb_wr(i2c1_sb_wr),
        .sb_stb(i2c1_sb_stb),
        .sb_addr(i2c1_sb_addr),
        .sb_data_i(i2c1_sb_data_i),
        .sb_data_o(i2c1_sb_data_o),
        .sb_ack(i2c1_sb_ack),
        .sb_irq(i2c1_irq),
        .quat_w(quat1_w),
        .quat_x(quat1_x),
        .quat_y(quat1_y),
        .quat_z(quat1_z),
        .gyro_x(gyro1_x),
        .gyro_y(gyro1_y),
        .gyro_z(gyro1_z),
        .data_valid(imu1_data_valid)
    );
    
    // BNO055 I2C Controller for IMU 2
    bno055_i2c_controller imu2_controller (
        .clk(clk),
        .rst_n(rst_n && i2c2_ready),
        .sb_clk(i2c2_sb_clk),
        .sb_wr(i2c2_sb_wr),
        .sb_stb(i2c2_sb_stb),
        .sb_addr(i2c2_sb_addr),
        .sb_data_i(i2c2_sb_data_i),
        .sb_data_o(i2c2_sb_data_o),
        .sb_ack(i2c2_sb_ack),
        .sb_irq(i2c2_irq),
        .quat_w(quat2_w),
        .quat_x(quat2_x),
        .quat_y(quat2_y),
        .quat_z(quat2_z),
        .gyro_x(gyro2_x),
        .gyro_y(gyro2_y),
        .gyro_z(gyro2_z),
        .data_valid(imu2_data_valid)
    );
    
    // Rest of your design (quaternion-to-Euler, gesture recognition, etc.)
    // ... (same as your current drum_system_top.sv)

endmodule

